# Generated by Django 5.1 on 2024-08-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='no',
            field=models.IntegerField(default=1),
        ),
    ]
