# Generated by Django 5.1 on 2024-08-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
