# Generated by Django 5.1 on 2024-08-13 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_alter_vehicle_no_alter_vehicle_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='customoer',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='year',
        ),
    ]
